services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'forexdb'
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - '3306:3306'
    expose:
      - '3306'

# open -a docker
# docker compose up -d
# docker container rm -f $(docker container ls -aq)