logging:
  level:
    org.springframework:
      jdbc: DEBUG
      aop: DEBUG
    com.zaxxer.hikari: DEBUG
spring:
  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
  application:
    name: ZettaForEx
  datasource:
    url: >
      jdbc:mysql://localhost:3306/forexdb?
      createDatabaseIfNotExist=true&
      useUnicode=true&
      characterEncoding=UTF-8&
      useSSL=false&
      serverTimezone=UTC
    username: ${DB_PASS:root}
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      jakarta:
        persistence:
          shared-cache:
            mode: UNSPECIFIED
      hibernate:
        connection:
          time_zone: UTC
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    parameters:
      serverTimezone: UTC
api_layer:
  url: http://apilayer.net/api/live
  api_key: ${API_KEY:ceb6fe6e6124f728e0490ea83f9fbce8}
  base_currency_code: EUR
  all_currency_codes: AED,AFN,ALL,AMD,ANG,AOA,ARS,AUD,AWG,AZN,BAM,BBD,BDT,BGN,BHD,BIF,BMD,BND,BOB,BRL,BSD,BTC,BTN,BWP,BYN,BYR,BZD,CAD,CDF,CHF,CLF,CLP,CNY,COP,CRC,CUC,CUP,CVE,CZK,DJF,DKK,DOP,DZD,EEK,EGP,ERN,ETB,EUR,FJD,FKP,GBP,GEL,GGP,GHS,GIP,GMD,GNF,GTQ,GYD,HKD,HNL,HRK,HTG,HUF,IDR,ILS,IMP,INR,IQD,IRR,ISK,JEP,JMD,JOD,JPY,KES,KGS,KHR,KMF,KPW,KRW,KWD,KYD,KZT,LAK,LBP,LKR,LRD,LSL,LTL,LVL,LYD,MAD,MDL,MGA,MKD,MMK,MNT,MOP,MRO,MUR,MVR,MWK,MXN,MYR,MZN,NAD,NGN,NIO,NOK,NPR,NZD,OMR,PAB,PEN,PGK,PHP,PKR,PLN,PYG,QAR,RON,RSD,RUB,RWF,SAR,SBD,SCR,SDG,SEK,SGD,SHP,SLL,SOS,SRD,STD,SVC,SYP,SZL,THB,TJS,TMT,TND,TOP,TRY,TTD,TWD,TZS,UAH,UGX,USD,UYU,UZS,VEF,VND,VUV,WST,XAF,XAG,XAU,XCD,XDR,XOF,XPF,YER,ZAR,ZMK,ZMW,ZWL
